# Generated by Django 5.1.4 on 2025-03-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_patient_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='document_type',
            field=models.CharField(choices=[('prescription', 'Prescription'), ('xray', 'X-ray'), ('scan', 'Scan'), ('report', 'Report'), ('document', 'Document')], default='document', max_length=20),
        ),
    ]
